### ISSUE TITLE
1.2.0 版本在 Laravel 5.4.19 版本下图片保存失败问题

### ISSUE THREAD

**Issue by dullme** [overtrue/laravel-ueditor#11]
超哥 你的1.2.0版本在 Laravel 5.4.19 下图片保存到  App/public/uploads 下失败！
我换回用1.1.0版本 在  Laravel 5.4.19 下能正常保存图片

**Comment by overtrue** [comment]
@dullme 1.2.0 会保存到 storage 下，根据你的配置里的 disk 决定存到哪里。使用 `php artisan storage:link` 创建 public 软链接

**Comment by dullme** [comment]
创建软链接的话 是不是文件实际上是存在storage下面的？

**Comment by overtrue** [comment]
@dullme 是的
