### ISSUE TITLE
异常：Call to undefined method League\Flysystem\Filesystem::putFileAs

### ISSUE THREAD

**Issue by jiker-burce** [overtrue/laravel-ueditor#15]
"overtrue/laravel-ueditor": "~1.0",
ueditor.php:
    'disk' => 'public',

上传图片时出现：
[2017-05-20 16:52:06] local.ERROR: BadMethodCallException: Call to undefined method League\Flysystem\Filesystem::putFileAs in H:\wamp\www\gdyxh\vendor\league\flysystem\src\Plugin\PluggableTrait.php:90
Stack trace:
#0 [internal function]: League\Flysystem\Filesystem->__call('putFileAs', Array)
#1 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(350): call_user_func_array(Array, Array)
#2 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\StorageManager.php(125): Illuminate\Filesystem\FilesystemAdapter->__call('putFileAs', Array)
#3 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\StorageManager.php(60): Overtrue\LaravelUEditor\StorageManager->store(Object(Symfony\Component\HttpFoundation\File\UploadedFile), '/uploads/image/...')
#4 H:\wamp\www\gdyxh\vendor\overtrue\laravel-ueditor\src\UEditorController.php(43): Overtrue\LaravelUEditor\StorageManager->upload(Object(Illuminate\Http\Request))
#5 [internal function]: Overtrue\LaravelUEditor\UEditorController->serve(Object(Illuminate\Http\Request))
#6 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#7 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('serve', Array)
#8 H:\wamp\www\gdyxh\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Overtrue\LaravelUEditor\UEditorController), Object(Illuminate\Routing\Route), 'serve')

**Comment by overtrue** [comment]
laravel 什么版本？看看 这个文件：`/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php` 中是否有 putFileAs 方法

**Comment by jiker-burce** [comment]
5.1 版。只有put()方法。

**Comment by jiker-burce** [comment]
我将StorageManager的store修改为：
    protected function store(UploadedFile $file, $filename)
    {
        if(method_exists($this->disk,'putFileAs')){
            return $this->disk->putFileAs('', $file, $filename);
        }else{
            $realPath = $file->getRealPath();
            return $this->disk->put($filename,file_get_contents($realPath));
        }
    }
就可以正常上传到七牛了。
但是，UEditor的上传对话框还是会显示：服务器错误
对应laravel.log中的异常： BadMethodCallException: Call to undefined method League\Flysystem\Filesystem::url

**Comment by overtrue** [comment]
感觉你的配置不对，这里不应该调用 League\Flysystem\Filesystem 而是应该调用 Illuminate/Filesystem/FilesystemAdapter.php 中的 putFileAs 才对

**Comment by jiker-burce** [comment]
这里面也是只有put方法，没有putFileAs哦！
配置都是按照Readme来的呢。

**Comment by jiker-burce** [comment]
看了下laravel源代码，从5.3版开始FilesystemAdapter才有putFileAs方法。

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-ueditor/releases/tag/1.2.1
