### ISSUE TITLE
View [vendor.ueditor.assets] not found

### ISSUE THREAD

**Issue by ghost** [overtrue/laravel-ueditor#16]
![2](https://cloud.githubusercontent.com/assets/22977916/26281089/a758a236-3e1e-11e7-97d5-930f6b7f76e3.png)

laravel版本： 5.4.23
不知道为什么说这个模版不存在。。

在  laravel\framework\src\Illuminate\View\FileViewFinder.php line 137: 报了两个异常 ：
1. ErrorException
2. InvalidArgumentException

错误都是这个：
View [vendor.ueditor.assets] not found

PS：我在5.3的时候还是能够使用的。。

**Comment by overtrue** [comment]
你有 vendor publish 没？

**Comment by ghost** [comment]
我已经publish了啊。
```  bash
$ php artisan vendor:publish --provider='Overtrue\LaravelUEditor\UEditorServiceProvider'
```

**Comment by ghost** [comment]
``` bash
$ php artisan config:clear
```
运行一下，然后重新publish就好了。。

@overtrue 
辛苦了。

**Comment by overtrue** [comment]
OK
