### ISSUE TITLE
请教：如何通过你的七牛插件包分段上传大视频数据

### ISSUE THREAD

**Issue by jiker-burce** [overtrue/laravel-ueditor#17]
如题。3q！

**Comment by overtrue** [comment]
目前不支持分片上传哦，这块可以先自行实现，谢谢：https://developer.qiniu.com/kodo/api/1286/mkblk

**Comment by overtrue** [comment]
这个我考虑在该包里实现，这里先关了

**Comment by yl** [comment]
有考虑使用  [qiniu](https://github.com/qiniu) / [qetag](https://github.com/qiniu/qetag) 避免相同文件重复上传吗？
