### ISSUE TITLE
图片无法上传

### ISSUE THREAD

**Issue by mtgnorton** [overtrue/laravel-ueditor#21]
laravel5.3，将Filesystem.php中的路径改为public_path()后可以上传，但上传完图片后，ueditor请求的路径为 /storage//uploads/image/2017/05/25/3fe5450976edc225f8b690c1d5d683f3.jpeg

**Comment by overtrue** [comment]
不需要修改代码哦
```shell
$ php artisan storage:link 
```

**Comment by mtgnorton** [comment]
可以了，感谢
