### ISSUE TITLE
多图上传中，超过20张图，后面无法显示

### ISSUE THREAD

**Issue by jiker-burce** [overtrue/laravel-ueditor#23]
虽然后台提供了分页功能，但是在编辑器中下拉没有反应，也没有相应的下一页和上一页按钮。

**Comment by jiker-burce** [comment]
分析源代码后，已经发现问题。是UEditor在
/vendor/ueditor/dialogs/image/image.js的第874行逻辑判断有问题。
将 `if(_this.listIndex>= json.total) {` 修改为`if(_this.listSize > json.total) {`即可。
安兄看看是否会影响其他位置，没有的话，可以更新下代码哈。

**Comment by overtrue** [comment]
@BruceGujinhe 试试不要改 js, 改一下 PHP 看看
