### ISSUE TITLE
laravel5.4使用时文件会上传到storage文件夹导致图片无法显示

### ISSUE THREAD

**Issue by DamonSnow** [overtrue/laravel-ueditor#25]
laravel5.4使用ueditor上传的图片在disk为public时，文件的上传路径在laravel项目的storage文件夹中，不是在public文件夹。所以上传图片后会无法正常显示。

**Comment by DamonSnow** [comment]
解决了，原本没有php artisan storage:link，APP_URL也没有配置，导致的问题。

**Comment by overtrue** [comment]
:smile:
