### ISSUE TITLE
图片保存到/storage/app/public/uploads下

### ISSUE THREAD

**Issue by tina2017522** [overtrue/laravel-ueditor#27]
我的配置如下
`APP_URL=http://www.tina.com`

`'disk' => 'public',

`

然后我编辑器页面图片是破的 所以自己写了一个路由

`Route::get('/storage/uploads/image/{yy}/{mm}/{dd}/{file}',function($yy,$mm,$dd,$file){
    $image = "/Library/WebServer/Documents/stu2/storage/app/public/uploads/image/"."{$yy}/"."{$mm}/"."{$dd}"."/{$file}";
    header("Content-Type:image/jpeg");
    echo file_get_contents($image);
});`

现在可以显示了，但是非要这样写吗  为什么图片不到public下呢  

还有我为什么只能找到一些前台文件  处理图片上传的php代码 在什么目录呢 

谢谢！！！

**Comment by overtrue** [comment]
```sh
$ php artisan storage:link
```
