### ISSUE TITLE
图片上传，文件路径错误

### ISSUE THREAD

**Issue by wwhu668** [overtrue/laravel-ueditor#28]
前端提示

> GET http://test.app/storage/uploads/image/2017/06/27/b0bd1f8ad24ebc0e0fcc7a9360cfeeed.jpg 404 > (Not Found)

实际路径
> /storage/app/public/uploads/image/2017/06/27/b0bd1f8ad24ebc0e0fcc7a9360cfeeed.jpg

**Comment by overtrue** [comment]
哎，`$ php artisan storage:link`
