### ISSUE TITLE
没加入中间件控制上传

### ISSUE THREAD

**Issue by wenrouzei** [overtrue/laravel-ueditor#3]
1.上传没加入中间件控制

2.php7报错
ErrorException in StorageManager.php line 217:
 rand() expects parameter 2 to be integer, float given

**Comment by JellyBool** [comment]
@wenrouzei 

1.应该看自己的业务逻辑吧，你可以自己加一下。

2.这个应该 fixed 了的，具体可以看这个：https://github.com/overtrue/laravel-ueditor/commit/c59c297d11e6624d006bcf9a5187103281f91d12

**Comment by meitesi** [comment]
如果能设置成jellyBool 讲的知乎的那个视频里ueditor的主题，就更好了。

**Comment by JellyBool** [comment]
那个是简单的版本，要是可以的话，我也可以直接把那个主题迁移过来。

@meitesi

**Comment by meitesi** [comment]
期待啊 哈哈

**Comment by thirdriver** [comment]
@JellyBool 支持迁移那个版本

**Comment by overtrue** [comment]
@JellyBool 主题你另外开一个 issue 吧

**Comment by overtrue** [comment]
@wenrouzei 已经加入路由组选项支持，配置文件里的 route 部分：

```php
 'route' => [
        'name' => '/ueditor/server',
        'options' => [
            // middleware => 'auth',  你可以在这里自由发挥了
        ],
    ],
```
