### ISSUE TITLE
windows下使用laravel5.1安装后，发布配置文件与资源，无法生成config/ueditor.php文件

### ISSUE THREAD

**Issue by xinhaonaner** [overtrue/laravel-ueditor#35]
php artisan vendor:publish --provider='Overtrue\LaravelUEditor\UEditorServiceProvider'
敲完后，提示 Nothing to publish for tag [].是软连接的问题吗？

**Comment by overtrue** [comment]
\ -> \\\\

**Comment by xinhaonaner** [comment]
**超哥，这表情，我有点懵逼哈**

**Comment by overtrue** [comment]
@xinhaonaner 谁说是表情了，让你把单斜线写成双斜线

**Comment by luzhang2010** [comment]
Laravel 5.4 windows publish确实没能复制文件，改成双斜杠也没起色。同等条件下再centos里面就行。
centos下：
Copied File [/vendor/overtrue/laravel-ueditor/src/config/ueditor.php] To [/config/ueditor.php]
Copied Directory [/vendor/overtrue/laravel-ueditor/src/assets/ueditor] To [/public/vendor/ueditor]
Copied Directory [/vendor/overtrue/laravel-ueditor/src/views] To [/resources/views/vendor/ueditor]
Copied Directory [/vendor/overtrue/laravel-ueditor/src/translations] To [/resources/lang/vendor/ueditor]
windows下,仅提示：
Publishing complete.

**Comment by overtrue** [comment]
那我就没办法了...
