### ISSUE TITLE
windows下laravel5.4,上传图片,图片无法显示 

### ISSUE THREAD

**Issue by gitjungle** [overtrue/laravel-ueditor#37]
- 查看了下,图片保存到了`storage\app\public\uploads\....`里面
- 但图片显示的地址是根目录的`public\uploads\.....`里面
- 所以导致无法显示图片,这个....弄了半天,没搞定....配置是按说明文档上来的,我是本地开发...

**Comment by overtrue** [comment]
1 .5.3 以下，我在 README 说明了，你肯定没看，如下图
![image](https://user-images.githubusercontent.com/1472352/28821852-acc30abe-76e9-11e7-9934-ffc4f250538e.png)

2. 5.4+  官方就说了 `./artisan storage:link`
