### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by jiker-burce** [overtrue/laravel-ueditor#40]
配置，上传都是ok，就是在最后一步显示有问题。看碰到过这种情况没？跟编译环境有关吗？
单步调试情况，第24472行报的错：Uncaught SyntaxError: Unexpected identifier
    at new Function (<anonymous>)

如果七牛包是
`
"qiniu/php-sdk": "^7.1",
`
这样加入到composer.json文件中，将会出这样的现象：“上传错误”，“本地保存成功”。
必须把7.1前面的"^"去掉就可以正常上传和显示，也就是目前超兄的ueditor七牛插件包只支持7.1版本的。
7.2版本的在24471行的result返回的值前面有“ query from “字样（这个是7.2中 vendor/qiniu/php-sdk/src/Qiniu/Config.php的getZone() 在返回结果时自动加上的），正是这个导致ueditor前端无法正常解析和显示图片。

望超兄有空时更新下。

**Comment by overtrue** [comment]
有截图么？

**Comment by jiker-burce** [comment]
你在composer.json 里面把七牛sdk改成:`"qiniu/php-sdk": "7.2",`,然后再随便写个页面加载下ueditor容器，然后点击里面的单图或者多图上传，就会提示这个：“上传错误”，“本地保存成功”。
把`"qiniu/php-sdk": "^7.1"` 改成 `"qiniu/php-sdk": "7.1"`就没问题了。

**Comment by overtrue** [comment]
PHP 版本问题吧
