### ISSUE TITLE
配置qiniu后返回的数据里url有2个斜杠

### ISSUE THREAD

**Issue by daisanmu** [overtrue/laravel-ueditor#43]
{"state":"SUCCESS","url":"http:\/\/ow3prqlyx.bkt.clouddn.com\/\/uploads\/image\/2017\/09\/11\/87a7a8f6d3fb0151f93f6f8b9e582cec.gif","title":"\/uploads\/image\/2017\/09\/11\/87a7a8f6d3fb0151f93f6f8b9e582cec.gif","original":"vip.gif","type":"","size":151}

**Comment by overtrue** [comment]
请更新 overtrue/flysystem-qiniu 到 1.0.1
