### ISSUE TITLE
图片上传不显示问题

### ISSUE THREAD

**Issue by deliangyang** [overtrue/laravel-ueditor#46]
图片上传后返回的访问地址不对，/etc/hosts www.xx.com 配置后返回的localhost

**Comment by use4testing** [comment]
项目根目录\vendor\overtrue\laravel-ueditor\src\StorageManager.php
 public function upload函数里
$response = [
            'state' => 'SUCCESS',
            'url' => 'storage/'.$filename,  改这个就好了

**Comment by souail1** [comment]
.env上修改APP_URL，把localhost改成你的域名
