### ISSUE TITLE
google地图无法正确加载

### ISSUE THREAD

**Issue by kacheStudio** [overtrue/laravel-ueditor#50]
![a yyz9ql3d s 56 bwaa34v](https://user-images.githubusercontent.com/22138770/34678215-57eeee9e-f48a-11e7-8942-60f969b10c8a.png)

**Comment by overtrue** [comment]
Google 地图。。。你觉得能正常加载？

**Comment by kacheStudio** [comment]
好吧，我表示抱歉，我忘记说明了，我在国外~，包括服务器。
我发现并不是 laravel-ueditor 的问题，我从官网下载了 ueditor，在本地没有问题，服务器上就出现了问题~ 这点让我很困扰

**Comment by overtrue** [comment]
@DevXlh 看看控制台报啥错
