### ISSUE TITLE
发布文件时的写法错误

### ISSUE THREAD

**Issue by seth-shi** [overtrue/laravel-ueditor#52]
`php artisan vendor:publish --provider='Overtrue\LaravelUEditor\UEditorServiceProvider'`
不应该用引号包围起来
`php artisan vendor:publish --provider=Overtrue\LaravelUEditor\UEditorServiceProvider`

**Comment by overtrue** [comment]
结果上有区别么？

**Comment by seth-shi** [comment]
https://imgchr.com/i/91qkKP
https://imgchr.com/i/91qADf

图片中，多了引号，导致解析不出这个服务提供者

**Comment by overtrue** [comment]
额好吧，windows ... 你试试用双引号
