### ISSUE TITLE
Laravel5.2使用监听事件Overtrue\LaravelUEditor\Events\Uploaded失败

### ISSUE THREAD

**Issue by zhong2peng** [overtrue/laravel-ueditor#54]
我在EventListener注册了监听Overtrue\LaravelUEditor\Events\Uploaded事件的处理，在上传图片成功后，$this->eventSupport()返回的结果为false，然后查看寻找Illuminate\Foundation\Events\Dispatchable，没有此文件，应该是laravel5.4之后引入的吧！请问要监听上传成功事件后做处理，该怎么做？

**Comment by overtrue** [comment]
@zhong2peng 更新 Laravel 版本吧，我没时间去兼容旧版，5.2 到 5.4 并没有太多变化。
