### ISSUE TITLE
跨域问题！！

### ISSUE THREAD

**Issue by Linij** [overtrue/laravel-ueditor#58]
在域名为admin.dev.xxx.com中引用这个轮子，
跨域方案是用了laravel-cors轮子。

发起图片上传请求的时候检测不到request中的Origin导致跨域轮子不允许上传。
![image](https://user-images.githubusercontent.com/8857514/44835674-72a7ab00-ac67-11e8-86af-e1c48b8b3342.png)

**Comment by overtrue** [comment]
无法重现
