### ISSUE TITLE
无法使用laravel-admin的中间件

### ISSUE THREAD

**Issue by sean1990** [overtrue/laravel-ueditor#59]
'route' => [
        'name' => '/ueditor/server',
        'options' => [
            'middleware' => 'admin',
        ],
    ],
已经配置成上面的这个admin中间件了，但是在laravel-admin里面还是无法上传图片。如果把这段注释掉就能上传了，但是那样不安全了。

**Comment by overtrue** [comment]
提问请提供详细的上下文说明，我是一个凡人，所以我无法猜测以下问题：

1. admin 中间件是什么？内容是啥？
2. 你所谓的 “无法上传图片”，现象是什么？报错是什么？

**Comment by eddy8** [comment]
如果你是自定义的登录认证中间件，需要把web中间件也加上才可以。
`'middleware' => ['web', 'admin']`

**Comment by sean1990** [comment]
> 
> 
> 如果你是自定义的登录认证中间件，需要把web中间件也加上才可以。
> `'middleware' => ['web', 'admin']`
我有试过的不行，后来我直接吧中间件这行注释掉了。就能上传了
貌似admin的中间件不能在这个上传里面使用，Laravel-admin是一个单独的包，它的中间件貌似不是整个项目通用。

**Comment by overtrue** [comment]
https://github.com/laravel-admin-extensions/UEditor
