### ISSUE TITLE
laravel-admin后台扩展编辑器。单图上传失败，多图可以

### ISSUE THREAD

**Issue by yishui01** [overtrue/laravel-ueditor#61]
服务端返回是成功的json，但浏览器一直报警告说期望文档类型却返回个json。
![image](https://user-images.githubusercontent.com/20850040/50500407-08274000-0a8c-11e9-8838-78d50bf2bf5a.png)

![image](https://user-images.githubusercontent.com/20850040/50500270-22145300-0a8b-11e9-968f-56730ff5ec0c.png)
![image](https://user-images.githubusercontent.com/20850040/50500277-38221380-0a8b-11e9-93bb-6ce5849b5463.png)
![image](https://user-images.githubusercontent.com/20850040/50500331-93540600-0a8b-11e9-8781-6dd48670f519.png)
猜测是js解析返回结果的时候，没把他当做json来解析，然后找到ueditor.all.js  24468行，修改result解析结果为JSON.parse(result)
![image](https://user-images.githubusercontent.com/20850040/50500337-a49d1280-0a8b-11e9-99ec-cda1431872d9.png)
问题解决，但是TMD还是报期望文档却返回个json
![image](https://user-images.githubusercontent.com/20850040/50500407-08274000-0a8c-11e9-8838-78d50bf2bf5a.png)
多图上传不会出现这个警告，并且上传正常，总感觉是这个ue.all.js的锅

**Comment by never615** [comment]
wo zhe ke yi.
