### ISSUE TITLE
用composer安装出现错误怎么办

### ISSUE THREAD

**Issue by alexanderlinjin** [overtrue/laravel-ueditor#64]
G:\phpproject>composer require "overtrue/laravel-ueditor:~1.0"

  [Composer\Downloader\TransportException]
  The "https://packagist.phpcomposer.com/p/provider-2018-10%249c217adcadf15445dab9f24104bd5d381b4ed22bf9fff2ea3e3fd87a7d2637d4.json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by overtrue** [comment]
因为你用的源已经没人维护了。phpcomposer.com 已经停止维护了，请使用官方或者微信 learnku.com 提供的。


alexanderlinjin <notifications@github.com>于2019年3月17日 周日下午4:52写道：
