### ISSUE TITLE
上传功能将不能正常使用

### ISSUE THREAD

**Issue by bytecc-coder** [overtrue/laravel-ueditor#65]
请求后台配置项http错误，上传功能将不能正常使用！

**Comment by overtrue** [comment]
确保 `https://你的域名/ueditor/server?action=config` 能正确访问，如果不能，可能是因为你前置了其它中间件

**Comment by KeepXin** [comment]
接口返回上传成功
`{state: "SUCCESS",…}
original: "1.jpg"
size: 385063
state: "SUCCESS"
title: "/uploads/image/2019/03/31/126efe845a27d84bad1b88aa31f8bbfc.jpg"
type: ""
url: "http://myurl/storage/uploads/image/2019/03/31/126efe845a27d84bad1b88aa31f8bbfc.jpg"`

但是实际上传失败，这是什么原因啊？

**Comment by KeepXin** [comment]
上面http://你的域名/ueditor/server?action=config 也能访问成功

**Comment by overtrue** [comment]
> 接口返回上传成功
> `{state: "SUCCESS",…} original: "1.jpg" size: 385063 state: "SUCCESS" title: "/uploads/image/2019/03/31/126efe845a27d84bad1b88aa31f8bbfc.jpg" type: "" url: "http://myurl/storage/uploads/image/2019/03/31/126efe845a27d84bad1b88aa31f8bbfc.jpg"`
> 
> 但是实际上传失败，这是什么原因啊？

检查你的 storage/app/public 目录下。

**Comment by KeepXin** [comment]
多谢反馈~
`/storage/uploads/image/2019/04/01/6d01382261599e90fa64f9e0abb58c26.jpg`
检查上面目录下是有文件的，就是上传成功了，访问404，访问路径为
`http://我的域名//storage/uploads/image/2019/04/01/6d01382261599e90fa64f9e0abb58c26.jpg`
这是什么原因啊，是我需要哪里配置上传路径吗？我想要上传到public下，公开访问。

**Comment by overtrue** [comment]
你需要仔细阅读文档，还有了解 Laravel 的使用。

```bash
$ php artisan storage:link
```

KeepXin <notifications@github.com>于2019年4月1日 周一下午5:31写道：

**Comment by overtrue** [comment]
并且，我在说明里第一句话就讲了：https://github.com/overtrue/laravel-ueditor/blob/master/README.md#%E8%AF%B4%E6%98%8E
