### ISSUE TITLE
文件名解析问题

### ISSUE THREAD

**Issue by RealZark** [overtrue/laravel-ueditor#66]
问题文件：`StorageManager.php`
![image](https://user-images.githubusercontent.com/16811858/55681392-af075c00-5958-11e9-992a-28ea93e65d2e.png)
对于微信公众号文章内的图片链接是这样的：
```
https://mmbiz.qpic.cn/mmbiz_jpg/vBKJ934geNIQSl9xz5OwpsoKy7gCCr8kYZSKDcM6mUNG0rUbUyDqeVYgMCyvkRYKq5sLusPL9uj9iaJ38XeGoKQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1
```
如果使用 `$img->getFilename()` 这种方式获取图片名称的话，复制微信公众号文章的时候，所有图片获取到的图片名称永远都是这样的：
```
640
```
就会导致永远都只会上传一张图片，后面的图片都不会上传，由于名称一样，所有图片的地址也都替换成最初上传的那张图片链接。为什么不直接对传到后台的图片链接进行 `md5` 操作？

有说的不对的地方请指正，谢谢！

**Comment by overtrue** [comment]
你提个 PR 吧
