### ISSUE TITLE
what does ueditor's demo file mean?

### ISSUE THREAD

**Issue by miaotaizi** [overtrue/laravel-ueditor#9]
Why publish it to `public/vendor` folder ?

**Comment by overtrue** [comment]
@miaotaizi 难道你们家的 web 服务中静态文件不放到 public 下能访问？

**Comment by miaotaizi** [comment]
@overtrue .php 是静态文件吗?

**Comment by overtrue** [comment]
@miaotaizi sorry, 那些文件根本没有参与整个项目的运行。。。

**Comment by miaotaizi** [comment]
@overtrue 那是不是不要放进去比较好?

**Comment by overtrue** [comment]
@miaotaizi 嗯
